# -*- coding: utf-8 -*-
"""gestao_estoque_nome_aluno.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198kPtaFKeLW3lYLrUsyKOjX2x9gNUcSM
"""

estoque = [
    {
        "id": 1,
        "nome": "Morango",
        "categoria": "Frutas",
        "preco": 6.00,
        "quantidade": 10
    }
]

proximo_id = 2

def cadastrar_produto(nome, categoria, preco, quantidade):
    """Registra novo produto no sistema"""
    global proximo_id
    nome = input("Digite o nome do produto: ")
    categoria = input("Digite a categoria do produto: ")
    preco_str = input("Digite o preço do produto: ")
    preco = float(preco_str.replace(',', '.'))
    quantidade = int(input("Digite a quantidade do produto: "))
    produto = {
        "id": proximo_id,
        "nome": nome,
        "categoria": categoria,
        "preco": preco,
        "quantidade": quantidade
    }
    estoque.append(produto)
    print(f"Produto cadastrado com sucesso! ID: {proximo_id}")
    proximo_id += 1

def registrar_entrada(produto_id, quantidade):
    """Adiciona itens ao estoque"""
    for produto in estoque:
        if "id" in produto and produto["id"] == produto_id:
            produto["quantidade"] += quantidade
            print("Entrada registrada com sucesso!")
            return
    print("Produto não encontrado.")


def registrar_saida(produto_id, quantidade):
    """Remove itens do estoque"""
    for produto in estoque:
        if "id" in produto and produto["id"] == produto_id:
            if produto["quantidade"] >= quantidade:
                produto["quantidade"] -= quantidade
                print("Saída registrada com sucesso!")
                return
            else:
                print("Quantidade insuficiente em estoque.")
                return
    print("Produto não encontrado.")


def consultar_estoque(produto_id):
    """Verifica saldo atual do produto"""
    for produto in estoque:
        if "id" in produto and produto["id"] == produto_id:
            print(f"Saldo atual do produto {produto['nome']} (ID: {produto['id']}): {produto['quantidade']}")
            return
    print("Produto não encontrado.")


def alertar_estoque_baixo(limite):
    """Identifica produtos com estoque crítico"""
    for produto in estoque:
        if produto["quantidade"] <= limite:
            print(f"Estoque baixo para o produto {produto['nome']} (ID: {produto['id']}). Quantidade atual: {produto['quantidade']}")



def mostrar_relatorio():
    if not estoque:
        print("Nenhum produto cadastrado.")
        return
    print("\n--- Relatório de Estoque ---")
    for produto in estoque:
        print(f"ID: {produto['id']}")
        print(f"Nome: {produto['nome']}")
        print(f"Categoria: {produto['categoria']}")
        print(f"Preço: R$ {produto['preco']:.2f}")
        print(f"Quantidade: {produto['quantidade']}")
    print("---------------------------\n")


while True:
  print("Escolha uma opção:")
  print("1 - Adicionar produto")
  print("2 - Mostrar relatório de estoque")
  print("3 - Sair")
  opcao = input()
  if opcao == "1":
    cadastrar_produto(None, None, None, None)
  elif opcao == "2":
    mostrar_relatorio()
    alertar_estoque_baixo(5)
    print("Escolha uma opção:")
    print("1 - Registrar entrada")
    print("2 - Registrar saída")
    print("3 - Consultar estoque")
    print("4 - Voltar ao menu principal")
    opcao_submenu = input()
    if opcao_submenu == "1":
      try:
        produto_id = int(input("Digite o ID numérico do produto para entrada: "))
        quantidade = int(input("Digite a quantidade a ser adicionada: "))
        registrar_entrada(produto_id, quantidade)
      except ValueError:
        print("Entrada inválida. O ID do produto e a quantidade devem ser números inteiros.")
    elif opcao_submenu == "2":
      try:
        produto_id = int(input("Digite o ID numérico do produto para saída: "))
        quantidade = int(input("Digite a quantidade a ser removida: "))
        registrar_saida(produto_id, quantidade)
      except ValueError:
        print("Entrada inválida. O ID do produto e a quantidade devem ser números inteiros.")
    elif opcao_submenu == "3":
      try:
        produto_id = int(input("Digite o ID numérico do produto para consulta: "))
        consultar_estoque(produto_id)
      except ValueError:
        print("Entrada inválida. O ID do produto deve ser um número inteiro.")
    elif opcao_submenu == "4":
      continue
    else:
      print("Opção inválida.")
  elif opcao == "3":
    print("Saindo do programa...")
    break